baseURL = 'https://russellgallinera.com'
languageCode = 'en-us'
title = "WIP"
theme = "nightfall"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 3

[menu]
  [[menu.header]]
    name = "resume"
    weight = 0
    url = "resume"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"

[params]
user = "russell"
hostname = "site"

# You can configure external links to open in new tabs by adding this parameter
openLinksInNewTab = true

displayDateFormat = "2006-01-02"

# Global metadata display settings
# Each can be overridden in individual post frontmatter
showMetadata = false # Master switch for all metadata display
showPublishedDate = false  # Show published date on post page
showReadingTime = false    # Show reading time on post page
showTags = false # Show tags on post page
showAuthors = false # Show authors on post page
showCategories = false # Show categories on post page

  [params.author]
    name = "RUSSELL GALLINERA"  # Website and RSS feed author
    email = "russellgallinera@gmail.com"  # RSS feed email address
#    avatar = "/images/avatar.jpg"  # Path to your avatar image
#    avatarSize = "size-m"  # Options: size-s, size-m, size-l
#    avatarFirst = true

[[params.social]]
key = 0
name = "[ github ]"
url = "https://github.com/d-tecnolife"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 2
name = "[ linkedin ]"
url = "https://www.linkedin.com/in/russell-gallinera-09a550291/"
aria = "LinkedIn Profile"

[[params.social]]
key = 3
name = "[ email ]"
url = "mailto:russellgallinera@gmail.com"
aria = "My Email Address"
